version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ../mosquitto_docker/config:/mosquitto/config
            - ../mosquitto_docker/data:/mosquitto/data
            - ../mosquitto_docker/log:/mosquitto/log
        networks:
            - mosquitto
        restart: always
networks:
    mosquitto:
        name: mosquitto
        driver: bridge